[in]
# flowmodels -> local parameters
# parameters that are not existing here will be ignored
"user/user_id" = "user_id"
"user/username" = "username"
"user/password" = "password"
"user/nickname" = "nickname"

[pre_out]
# "@remove" command will remove the given value from the flowmodels
"@remove" = "user"

[out]
# local parameters -> flowmodels
# possible paths: "user/username", "user/phone", "user/phone[1]" which are ALL valid paths(not valid path of definition)
"user_id" = "user/user_id"
"username" = "user/username"
"nickname" = "user/nickname"

[flow]
"steps" = [
    # invoke function - "@function" = [ parameter list ]
    { "@assign" = ["user_id", 123] }
]

