[in]
# flowmodels -> local parameters
# parameters that are not existing here will be ignored
# default value will be given based on the type of left if the left value not exist
# Note: Execution order is not defined. Don't rely on the order.
"user/user_id" = "user_id"
"user/username" = "username"
"user/password" = "password"
"user/nickname" = "nickname"

[pre_out]
# "@remove" command will remove the given value from the flowmodels
# Note: Execution order is not defined. Don't rely on the order.
"@remove" = "user"

[out]
# local parameters -> flowmodels
# possible paths: "user/username", "user/phone", "user/phone[1]" which are ALL valid paths(not valid path of definition)
# default value will be  based on the type of right if the left value not exist
# Note: Execution order is not defined. Don't rely on the order.
"user_id" = "user/user_id"
"username" = "user/username"
"nickname" = "user/nickname"

[flow]
"steps" = [
    # invoke function - "@function" = [ parameter list ]
    { "@assign" = ["user_id", 123] },
    # invoke user defined function
    { "#print_obj" = ["user_id"] },
]

