[pipelines.posts_new_post]
metadata.version = "1.0"
pipeline.source_connectors = [
    { "@connector" = "http_rest", "@mapping" = "http_inst", "http.listen" = "0.0.0.0:8081", "http.method" = "post", "http.path" = "/posts/new" }
]
pipeline.steps = [
    { "@flow" = "new_post_validation" },
    { "@flow" = "&database_postgres", "@mapping" = "query_user", "database.connect_string" = "postgres://admin:admin@192.168.1.111:25432/forum", "database.operation" = "query", "database.sql" = """
        select user_id, password from \"user\" where username = $1""" },
    { "@flow" = "login_user_existing_check" },
    { "@flow" = "login_check_password" },
]
[pipelines.posts_new_post.connector_mapping.http_inst]
req = [
    ["user/username", "http/body/username"],
    ["user/password", "http/body/password"],
]
res = [
    ["user/user_id", "http/body/user_id"],
]

[flows.new_post_validation]
in = [
    ["user/user_id", "user_id"],
]
flow.steps = [
    { "@check_not_blank_break" = ["user_id", "check_missing_user", "user not found"] }
]
